[server]
headless = true
enableCORS = false
maxUploadSize = 2048  # ✅ 2GB upload limit

[theme]
base = "light"
primaryColor = "#1f77b4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#000000"
font = "sans serif"

